### ISSUE TITLE
ModuleNotFoundError: No module named 'experiments'

### ISSUE THREAD

**Issue by jtwty** [nickjiang2378/vl-interp#2]
Hi, when I run the file named "run_llava.py", it uses a function called "coco_img_id_to_path" that from "experiments.blip_utils", but i can't find this path. I find the "blip_utils" under "methods", but also don't have this function.

Could you help me to solve this problem? Thanks

**Comment by nickjiang2378** [comment]
Thanks for reporting this! I just pushed a fix to the demos folder - could you see if it works for you? You can do `VL_ROOT_DIR=/path/to/dir python3 run_llava.py`

**Comment by jtwty** [comment]
OK, it works for me now. Thank you
