### ISSUE TITLE
The conflicts between "object_erasure.ipynb" and "llava_utils.py"

### ISSUE THREAD

**Issue by jtwty** [nickjiang2378/vl-interp#3]
Hello, Thanks for your good works!
But I find some problems between "object_erasure.ipynb" and "llava_utils.py".

First, in "object_erasure.ipynb", you wrote

```
loaded_state = load_llava_state(model_type, train = True)
```

but load_llava_state only has one parameter named device.

Then， the load_llava_state function's returns includes
```
return {
        "vocabulary": vocabulary,
        "vocab_embeddings": vocab_embeddings,
        "tokenizer": tokenizer,
        "execute_model": execute_model,
        "register_hook": register_hook,
        "register_pre_hook": register_pre_hook,
        "hidden_layer_embedding": hidden_layer_embedding,
        "model": model,
        "model_name": model_name,
        "image_processor": image_processor,
    }
```
but load data in "object_erasure.ipynb"
```
data = loaded_state["data"]
```

**Comment by nickjiang2378** [comment]
Thanks for letting us know! Can you try it again to see that it's working for you?

**Comment by jtwty** [comment]
OK! It's works for me
