### ISSUE TITLE
 Details of hallucination detection

### ISSUE THREAD

**Issue by CikZ2023** [nickjiang2378/vl-interp#4]
Thank you for your excellent work, but I still have some questions that need your clarification.
In the section 5.2 HALLUCINATION REMOVAL, you mentioned the elimination of hallucinations, but the premise is knowing what hallucinations are. According to your paper, you detect the internal confidence of each entity. I am curious about how you identify all possible hallucinatory entities, or how this entity is selected. Is it by calculating the confidence for all possible entities in the COCO dataset to detect hallucinations?

**Comment by nickjiang2378** [comment]
Thank you for the question. We are specifically looking at the 80 COCO object classes that CHAIR supports. We compute the confidence of any COCO object that appears in the image caption and remove it if it has low confidence. See the `demos` folder for examples of how to compute internal confidences.

**Comment by CikZ2023** [comment]
Thank you for your response. Based on your answer, I would like to confirm which method you use to detect hallucinations: 1. For an image, first let the large model generate a response, then detect the internal confidence of all objects involved in the generated response to determine hallucinations, 2. For any image, detect the internal confidence of 80 COCO object classes.

**Comment by nickjiang2378** [comment]
It's option 1. We have two total forward passes to remove hallucinations. We didn't use option 2, but that'd be a good direction to explore for cutting computational costs.

**Comment by CikZ2023** [comment]
Thank you for your explanation!!!

**Comment by JCSTARS** [comment]
Thanks for your awesome work! I tried to use the option2 in my experiment, and it turns out that it does not work as well as I expected. However, option 1 always works.
I assume that high internal confidence might be a necessary condition but not a sufficient condition for the objects that occur in an image.

**Comment by nickjiang2378** [comment]
That's an interesting observation - thanks for running that experiment!
